version: '2'
services:
    mywebapp:
        build: .
        container_name: ewdemo_webapp
        ports:
            - 3001:3001
        environment:
            - NODE_ENV=production
        depends_on:
            - influxdb
            - grafana
        links:
            - influxdb
            - grafana
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        ports:
            - 8086:8086
        env_file:
            - 'env.influxdb'
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - 3000:3000
        links:
            - influxdb